language: python
python:
  - "pypy"
  - "pypy3"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.5-dev"
  - "3.6-dev"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: "pypy"
    - python: "2.7"
    - python: "3.4"
    - python: "nightly"

install:
  - pip install -r requirements.txt

script:
  - exit 0