language: python
# Raspbian is running python 3.5, slackclient requires Python '>=3.6.0'
python:
  - "3.6"
  - "3.7"
  - "3.5-dev"
  - "3.6-dev"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: "nightly"

install:
  - pip install -r requirements.txt

script:
  - exit 0